Feature - Sessões Página Inicial
naygo/hubi pull request #10
Opened 2023-05-30 23:00 UTC by naygo

2023-06-06 02:59 UTC, HugoJF requested changes
Larguei uns comentários

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/pages/index.tsx
> +const heightFirstSection = 'calc(100vh - 71px)'
dúvida: pq separar em uma variável separada se usado em apenas 1 lugar? o nome da variável é quase maior que o conteudo

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/pages/index.tsx
> +            src={'https://picsum.photos/800/400?random=1'}
dúvida: era pra ainda estar usando o picsum?

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/pages/index.tsx
> +            src={'https://picsum.photos/800/400?random=2'}
dúvida: era pra ainda estar usando o picsum?

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/pages/index.tsx
> +              {team.map((member) => TeamMemberInfo(member))}
sugestão: recomendaria utilizar a sintaxe "normal" do React para componentes (`<TeamMemberInfo {...member} />`) para deixar claro que é um componente (eu tive que procurar a definição de `TeamMemberInfo` para entender completamente o que estava acontecendo.

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/pages/index.tsx
> +        alt="Random Image"
sugestão: na pior das situações deixaria como "Foto do membro do time", mas acho que faz sentido jogar essa variável para as props também.

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/shared/utils/icons.ts
> +  ['email']: FaEnvelope,
dúvida: pq envolver com `['` e `']`?

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/styles/globals.scss
> +    background-image: linear-gradient(to top, #0D0D0D,#1F1F1F);
sugestão: se essas cores existem na paleta do TailwindCSS, recomendo utilizar aqui com o helper `@apply`, também manteria o `global.scss` inteiro utilizando o `@apply` puramente por uma questão de consistência.

2023-06-06 02:59 UTC, HugoJF commented on packages/web/src/styles/colors.ts
> +export const yellowDefault = '#e09600'
dúvida: não consegui achar uso desse cara

2023-06-06 12:12 UTC, naygo commented on packages/web/src/pages/index.tsx
> +            src={'https://picsum.photos/800/400?random=1'}
yes, não estamos com as imagens oficiais ainda

2023-06-06 23:17 UTC, naygo commented on packages/web/src/styles/colors.ts
> +export const yellowDefault = '#e09600'
eu usava antes porque achei que as classes do tailwind não funcionavam em svgs, mas funcionam ai parei de usar isso e esqueci de apagar rs

2023-06-12 20:15 UTC, HugoJF approved these changes
🕊️ voe PR, voe 🕊️

2023-06-12 21:21 UTC, merged