Feature/login
naygo/hubi pull request #16
Opened 2023-06-21 00:52 UTC by naygo

- Tela de login
- Add next-auth e mock de login

2023-06-27 00:07 UTC, HugoJF requested changes

2023-06-27 00:07 UTC, HugoJF commented on packages/web/src/pages/api/auth/[...nextauth].ts
> +      },
não entendi, não era para estar implementado?

2023-06-27 00:07 UTC, HugoJF commented on packages/web/src/screens/login/form/index.tsx
> +  }
pq tanto console.log? não tem feedback para o usuário sobre o login?

2023-06-27 00:07 UTC, HugoJF commented on packages/web/src/shared/components/ui/navbar/index.tsx
> +  console.log(session, status)
console.log perdido aqui

2023-07-11 23:28 UTC, naygo commented on packages/web/src/pages/api/auth/[...nextauth].ts
> +      },
ainda não, isso foi feito antes do backend do login

2023-07-30 00:14 UTC, merged