Navbar e Footer
naygo/hubi pull request #9
Opened 2023-05-23 00:59 UTC by naygo

2023-05-23 02:21 UTC, HugoJF commented on packages/web/src/pages/_app.tsx
> +      </div>
dúvida: qual o ponto desse `h-full`? pelo que eu entendi, tu quer criar um container que já vai ocupar a tela toda, para jogar o `<Footer/>` para o final da página.

E nesse caso tu deveria fazer esse `h-screen` virar um `min-h-screen` para permitir que esse container cresça com conteúdo e esse container de `<Component />` deveria ter um `flex-grow` para que o ele ocupe todo o espaço disponível criado pelo `min-h-screen`.

2023-05-23 02:24 UTC, HugoJF commented on packages/web/src/shared/components/footer/index.tsx
> +  const link = 'text-gray-light font-bold hover:text-yellow cursor-pointer'
sugestão: ao invés de repetir essas classes entre as linhas 43 e 64, pq não fazer algo mais dinâmico? Evitaria repetição e a necessidade de criar essas variáveis

2023-05-23 02:26 UTC, HugoJF commented on packages/web/src/shared/components/footer/index.tsx
> +      <SocialMediaLinks isMobile />
dúvida: não entendi esse flag de mobile, isso é algo que deveria ser controlado via CSS, a princípio no breakpoint `sm`

2023-05-23 02:27 UTC, HugoJF commented on packages/web/src/shared/components/footer/styles.module.scss
> +.socialMediaBox {
sugestão: eu tentaria ao máximo evitar esse uso do TailwindCSS, tem certeza que não tem como usar ele diretamente aqui? O FeatherIcons eu nunca tive nenhuma limitação usando `className`.

2023-05-23 02:30 UTC, HugoJF commented on packages/web/src/shared/components/mobileNavbar/index.tsx
> +    <nav className="fixed top-[83px] left-0 right-0 bottom-0 w-screen h-screen z-50 bg-black p-4 flex flex-col gap-4">
sugestão: eu acho que entendi o approach do menu mobile, mas acho que ao invés de usar esse `top-[83px]` (pois ele vai quebrar no primeiro segundo que o conteúdo do teu navbar mudar), eu tentaria posicionar esse componente com um container `relative`.

2023-05-23 02:31 UTC, HugoJF commented on packages/web/src/shared/components/mobileNavbar/index.tsx
> +        <Button classStyle="primary" label="Jogar" />
sugestão: pelo amor troca esse `classStyle` por algo tipo `color` ou `type` :rofl:

2023-05-23 02:32 UTC, HugoJF commented on packages/web/src/shared/components/footer/index.tsx
> +import Logo from '../../../../public/img/logo.svg'
sugestão: eu vi tu usando `@public` em outro trecho, acho que poderia usar aqui também

2023-05-23 02:34 UTC, HugoJF commented on packages/web/src/shared/components/navbar/index.tsx
> +      <div className="min-[950px]:hidden">
sugestão: eu evitaria usar esses valores hardcoded (para esse caso) e focaria em manter breakpoints que fazem sentido (eles são customizáveis)

2023-05-23 02:35 UTC, HugoJF commented on packages/web/src/shared/components/navbar/index.tsx
> +            <div className="flex flex-col justify-between w-[20px] h-[20px] transform overflow-hidden">
sugestão: ao invés de definir vários width/heights fixos (o 20px e 50px), tu poderia fazer apenas o container 50px e centralizar ou a `div` interna 20px com padding no container de 15px. Vai depender do caso qual deles é mais adequado.

Em geral isso evita umas "surpresas" e faz teu componente um pouco mais maleável

2023-05-23 02:38 UTC, HugoJF requested changes
Larguei uns vários comentários que acho que valem a pena serem vistos.

2023-05-23 02:56 UTC, naygo commented on packages/web/src/shared/components/footer/index.tsx
> +      <SocialMediaLinks isMobile />
em desktop os links são exibidos acima dos outro links (linha 35), então o isMobile é pra identificar na função quando é o de baixo (linha 67) sendo renderizado a aplicar as classes certas

2023-05-24 22:37 UTC, mwives commented on packages/web/src/shared/components/mobileNavbar/index.tsx
> +    <nav className="fixed top-[83px] left-0 right-0 bottom-0 w-screen h-screen z-50 bg-black p-4 flex flex-col gap-4">
acho improvável a navbar mudar, já que só tem a logo nela. vamos manter assim

2023-05-25 00:16 UTC, HugoJF commented on packages/web/src/shared/components/footer/index.tsx
> +      <SocialMediaLinks isMobile />
sim sim, mas pq não usar CSS para isso?

2023-05-25 00:40 UTC, HugoJF commented on packages/web/src/shared/components/mobileNavbar/index.tsx
> +    <nav className="fixed top-[83px] left-0 right-0 bottom-0 w-screen h-screen z-50 bg-black p-4 flex flex-col gap-4">
Não é só uma questão de mudar o conteúdo, vocês tem 2 partes das navbar com posicionamentos diferentes, e isso torna a abordagem super inflexível e foi super rápido pra achar um bug no momento que adicionei algum conteudo pra permitir rolagem da tela por causa disso. 

[Screencast from 05-24-2023 08:37:19 PM.webm](https://github.com/naygo/hubi/assets/1527438/d9ed960c-e225-4a37-808a-c2cbdef92e50)

2023-05-25 04:23 UTC, HugoJF commented on packages/web/src/shared/components/footer/index.tsx
> +      </ReactLink>
sugestão: juntar esses links em uma lista e usar um `.map()` pra renderizar esses links, tem bastante repetição desnecessária

2023-05-25 04:28 UTC, HugoJF commented on packages/web/src/shared/components/mobileNavbar/index.tsx
> +  if (!isNavbarOpened) return null
brisa: eu já li esse trecho vezes o suficiente pra questionar se isso é uma boa, pessoalmente eu consigo me convencer facilmente que seria melhor fazer um "toggle" usando CSS (usando `clsx` e o `hidden`), pois isso evitaria fazer o React montar e desmontar toda essa árvore de elementos toda vez que a `navbar` for aberta.

Não acho que tem algo especificamente errado com esse `if` (apenas acho feio pra porra) mas fico extremamente curioso a respeito de performance (que também dá pra argumentar que nesse caso não vai ser muito significativo e lá lá lá, mas eu estou aqui pra ser chato)

2023-05-25 04:30 UTC, HugoJF commented on packages/web/src/shared/components/mobileNavbar/index.tsx
> +          <div
sugestão: eu não entendi o propósito desse segundo `<div>`, mas vou assumir que é para ser um container para qualquer elemento que o `<Link>` cria. Nesse caso eu recomendaria usar uma `<ul>` e `<li>` ao invés de `<div>` só por serem mais semânticos.

2023-05-25 04:38 UTC, HugoJF commented on packages/web/src/shared/components/navbar/index.tsx
> +        <nav className={`hidden min-[${mobileBreakpointInPx}px]:flex gap-4 text-gray`}>
bug: o TailwindCSS não consegue funcionar dinâmicamente, todas as classes usadas precisam ser estáticas para que elas possam ser geradas durante a build. Caso algum CSS seja necessariamente dinâmico, o correto seria usar o `style` diretamente.

Esse caso do breakpoint eu também sou super contra, o TailwindCSS já possui breakpoints nomeados e caso vocês não tenham alterado, o `sm` é 640px, e não tem nada perto de 950px.

Eu vou elaborar como aquele hook pode ser escrito evitando ter esse valor hardcoded.

2023-05-25 04:39 UTC, HugoJF commented on packages/web/src/shared/components/navbar/index.tsx
> +      <div className={`hidden min-[${mobileBreakpointInPx}px]:flex items-center gap-4`}>
bug: mesma coisa que eu comentei ali pra cima.

2023-05-25 04:39 UTC, HugoJF commented on packages/web/src/shared/components/navbar/index.tsx
> +      <div className={`min-[${mobileBreakpointInPx}px]:hidden`}>
bug: mesma coisa que eu comentei ali pra cima.

2023-05-26 23:25 UTC, HugoJF approved these changes

2023-05-26 23:26 UTC, merged